// This file is automatically generated pelo Lovable. Editado manualmente
// depois que o app passou a rodar fora do editor deles (GitHub Pages + APK
// Android) — nesses lugares não existe a "central" de preview do Lovable
// pra guardar a sessão, e qualquer tentativa de usá-la falhava com
// "Failed to fetch" (inclusive tentando ler a sessão salva sem internet,
// travando a abertura do app offline). Agora usa o armazenamento padrão do
// navegador (localStorage), que funciona em qualquer lugar.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: window.localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});